outward_codes = {
    # "outward_code": "district_name",
    "e1": "Head district",
    "e2": "Bethnal Green",
    "e3": "Bow",
    "e4": "Chingford",
    "e5": "Clapton",
    "e6": "East Ham",
    "e7": "Forest Gate",
    "e8": "Hackney",
    "e9": "Homerton",
    "e10": "Leyton",
    "e11": "Leytonstone",
    "e12": "Manor Park",
    "e13": "Plaistow",
    "e14": "Poplar",
    "e15": "Stratford",
    "e16": "Victoria Docks and North Woolwich",
    "e17": "Walthamstow",
    "e18": "Woodford and South Woodford",
    "e20": "Olympic Park",
    "ec1": "Head district",
    "ec2": "Bishopsgate",
    "ec3": "Fenchurch Street",
    "ec4": "Fleet Street",
    "n1": "Head district",
    "n2": "East Finchley",
    "n3": "Finchley",
    "n4": "Finsbury Park",
    "n5": "Highbury",
    "n6": "Highgate",
    "n7": "Holloway",
    "n8": "Hornsey",
    "n9": "Lower Edmonton",
    "n10": "Muswell Hill",
    "n11": "New Southgate",
    "n12": "North Finchley",
    "n13": "Palmers Green",
    "n14": "Southgate",
    "n15": "South Tottenham",
    "n16": "Stoke Newington",
    "n17": "Tottenham",
    "n18": "Upper Edmonton",
    "n19": "Upper Holloway",
    "n20": "Whetstone",
    "n21": "Winchmore Hill",
    "n22": "Wood Green",
    "nw1": "Head district",
    "nw2": "Cricklewood",
    "nw3": "Hampstead",
    "nw4": "Hendon",
    "nw5": "Kentish Town",
    "nw6": "Kilburn",
    "nw7": "Mill Hill",
    "nw8": "St John's Wood",
    "nw9": "The Hyde",
    "nw10": "Willesden",
    "nw11": "Golders Green",
    "se1": "Head district",
    "se2": "Abbey Wood",
    "se3": "Blackheath",
    "se4": "Brockley",
    "se5": "Camberwell",
    "se6": "Catford",
    "se7": "Charlton",
    "se8": "Deptford",
    "se9": "Eltham",
    "se10": "Greenwich",
    "se11": "Kennington",
    "se12": "Lee",
    "se13": "Lewisham",
    "se14": "New Cross",
    "se15": "Peckham",
    "se16": "Rotherhithe",
    "se17": "Walworth",
    "se18": "Woolwich",
    "se19": "Norwood",
    "se20": "Anerley",
    "se21": "Dulwich",
    "se22": "East Dulwich",
    "se23": "Forest Hill",
    "se24": "Herne Hill",
    "se25": "South Norwood",
    "se26": "Sydenham",
    "se27": "West Norwood",
    "se28": "Thamesmead",
    "sw1": "Head district",
    "sw2": "Brixton",
    "sw3": "Chelsea",
    "sw4": "Clapham",
    "sw5": "Earls Court",
    "sw6": "Fulham",
    "sw7": "South Kensington",
    "sw8": "South Lambeth",
    "sw9": "Stockwell",
    "sw10": "West Brompton",
    "sw11": "Head district",
    "sw12": "Balham",
    "sw13": "Barnes",
    "sw14": "Mortlake",
    "sw15": "Putney",
    "sw16": "Streatham",
    "sw17": "Tooting",
    "sw18": "Wandsworth",
    "sw19": "Wimbledon",
    "sw20": "West Wimbledon",
    "w1": "Head district",
    "w2": "Head district",
    "w3": "Acton",
    "w4": "Chiswick",
    "w5": "Ealing",
    "w6": "Hammersmith",
    "w7": "Hanwell",
    "w8": "Kensington",
    "w9": "Maida Hill",
    "w10": "North Kensington",
    "w11": "Notting Hill",
    "w12": "Shepherds Bush",
    "w13": "West Ealing",
    "w14": "West Kensington",
    "wc1": "Head district",
    "wc2": "Strand",
}
